fitnessfirst/diet/urls.py
from django.urls import path
from . import views

app_name = 'diet'

urlpatterns = [
    path('user-diet-plan/', views.user_diet_plan, name='user_diet_plan'),
]

fitnessfirst/fitnessfirst/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from users.views import index
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
    path('programs/', include('program.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name='password_reset_complete'),
    path('metrics/', include('metrics.urls')),
    path('diet/', include('diet.urls')),
]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

fitnessfirst/metrics/urls.py
# metrics/urls.py
from django.urls import path
from . import views

app_name = 'metrics'

urlpatterns = [
    path('calculate/', views.calculate_metrics, name='calculate_metrics'),
    path('results/<int:metric_id>/', views.results, name='results'),
]

fitnessfirst/templates/payment/payment_status.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fitness First</title>


    <link rel="stylesheet" href={% static 'app/css/style.css' %}>

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
      integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />

    <script src="https://kit.fontawesome.com/f6f8f493f3.js" crossorigin="anonymous"></script>

</head>
<body>
    <header class="header">
        <a href="#" class="logo"><i class="fa-solid fa-dumbbell"></i> Fitness <span>first</span></a>

        <nav class="navbar">
            <a class="nav-link scrollto" href="#">Home</a>
            <a class="nav-link scrollto" href="#feature">Programs</a>
            <a class="nav-link scrollto" href="#trainers">Trainers</a>
            <a class="nav-link scrollto" href="#about us">About Us</a>
            <a class="nav-link scrollto" href="#blogs">Blogs</a>
            <div class="dropdown">
                <a class="nav-link dropbtn" href="#">More</a>
                <div class="dropdown-content">
                    <a href="{% url 'metrics:calculate_metrics' %}">Metrics</a>
                    <a href="{% url 'diet:user_diet_plan' %}">Diet Plan</a>
                </div>
              </div>
        </nav>

        <div class="icons">
            {% if user.is_authenticated %}
            <a href={% url 'logout' %} class="btn">Logout</a>
            {% else %}
            <a href={% url 'login' %} class="btn">Join Us </a>
            {% endif %}

            <div id="menu-btn" class="fas fa-bars"></div>
        </div>
    </header>

    <!-- header section ends -->

    <div class="c">
        <img src={% static 'images/Fitness.gif' %} alt="">
        <h1 class="heading">Payment <span>Completed.</span></h1>
        {% comment %} <p>Your payment of <span> ₹{{program.price}}</span> is Successful!!</p> {% endcomment %}
        <p>Your payment for the <span> Fitness First Membership </span> is Successful!!</p>
        <p>Your booking has been confirmed. Now you are member of Fitness<span> First</span> Team.</p>
        <p>Welcome to Fitness First.</p>
        <a href="{% url 'index' %}" class="btn f">Go to Homepage</a><br>
    </div>
    <audio src="{% static 'payment_sound/gpay.mp3' %}" id="my_audio" ></audio> 


    <!-- footer section starts -->

    <section id="contact us" class="footer">

        <div class="box-container">

            <div class="box">
                <h1>About</h1>
                <div class="text">
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. 
                    Explicabo vero velit eum accusantium ullam, ratione deserunt 
                    placeat pariatur ut sit neque consequuntur eveniet</p>
                </div>
                <div class="icon">
                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                    <a href="#"><i class="fab fa-youtube"></i></a>
                    <a href="#"><i class="fab fa-instagram"></i></a>
                    <a href="#"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>

            <div class="box">
                <h1>Contact Info</h1>
                <div class="icons">
                    <a href="#"><i class="fas fa-map-marker-alt"></i>34 Street Name, city name here,
                     India</a>
                    <a href="#"><i class="fas fa-phone-alt"></i>+91 9619786756</a>
                    <a href="#"><i class="fas fa-envelope"></i>example@gmail.com</a>
                </div>
            </div>

            <div class="box">
                <h1>Quick Links</h1>
                <div class="icons">
                    <a href="#">Home</a>
                    <a href="#feature">Programs</a>
                    <a href="#blogs">Blogs</a>
                    <a href="#about us">About Us</a>
                    <a href="#contact us">Contact Us</a>
                </div>
            </div>

        </div>
    
        <div class="credit">Created by <span>Adarsh</span> | all right reserved</div>

    </section>

    <!-- footer section ends -->

    <style>

        .header{
            background: rgba(0,0,0,.9);
        }
        .c {
            text-align: center;
            margin: 2rem auto;
            padding-top: 10rem;
        }
        .c .heading{
            font-size: 3rem;
            padding-top: 0rem;
        }
        .c p{
            font-size: 2rem;
        }
        .c p span{
            font-weight: bold;
        }
        .c img{
            width: 300px;
            height: auto;
        }
        .c .f{
            margin-bottom: 3rem;
            margin-top: 2rem;
        }
        .c .btn{
            padding: 1rem 2rem;
        }
    </style>
    <script>

        document.getElementById("my_audio").play();
    
    </script>
</body>
</html>