fitnessfirst/diet/urls.py
from django.urls import path
from . import views

app_name = 'diet'

urlpatterns = [
    path('user-diet-plan/', views.user_diet_plan, name='user_diet_plan'),
]

fitnessfirst/fitnessfirst/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from users.views import index
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
    path('programs/', include('program.urls')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name='password_reset_complete'),
    path('metrics/', include('metrics.urls')),
    path('diet/', include('diet.urls')),
]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

fitnessfirst/metrics/urls.py
# metrics/urls.py
from django.urls import path
from . import views

app_name = 'metrics'

urlpatterns = [
    path('calculate/', views.calculate_metrics, name='calculate_metrics'),
    path('results/<int:metric_id>/', views.results, name='results'),
]

fitnessfirst/diet/models.py
from django.db import models
from django.conf import settings
from metrics.models import FitnessMetric

class DietCategory(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

class DietPlan(models.Model):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    ]

    category = models.ForeignKey(DietCategory, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    calories_per_day = models.IntegerField()
    # suitable_age_group = models.CharField(max_length=50, blank=True, null=True)  # E.g. '18-25', '25-40'
    min_bmi = models.FloatField(help_text="Minimum BMI for this diet plan", default='0')
    max_bmi = models.FloatField(help_text="Maximum BMI for this diet plan", default='50')
    gender = models.CharField(max_length=1, null=True, choices=GENDER_CHOICES, help_text="Gender suitability")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title



# New model that links users to diet plans
class UserDietPlan(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    diet_plan = models.ForeignKey(DietPlan, on_delete=models.SET_NULL, null=True)
    # assigned_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name="assigned_by")
    assigned_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.email}'s Diet Plan - {self.diet_plan.title if self.diet_plan else 'None'}"
    
    @staticmethod
    def assign_diet_plan_to_user(user):
        # Get the latest FitnessMetric for the user
        latest_metric = FitnessMetric.objects.filter(user=user).order_by('-date_calculated').first()

        if not latest_metric:
            return None  # No metrics available for the user
        
        # Query for a matching DietPlan based on BMI and gender
        diet_plan = DietPlan.objects.filter(
            min_bmi__lte=latest_metric.bmi,
            max_bmi__gte=latest_metric.bmi,
            gender=latest_metric.gender
        ).first()

        # Create or update the UserDietPlan
        if diet_plan:
            user_diet_plan, created = UserDietPlan.objects.update_or_create(
                user=user,
                defaults={'diet_plan': diet_plan}
            )
            return user_diet_plan
        return None  # No matching diet plan found

fitnessfirst/diet/views.py
from django.shortcuts import render
from .models import UserDietPlan, DietPlan
from metrics.models import FitnessMetric
from django.contrib.auth.decorators import login_required

@login_required
def user_diet_plan(request):

    try:
        user_metric = FitnessMetric.objects.filter(user=request.user).latest('date_calculated')
    except FitnessMetric.DoesNotExist:
        user_metric = None

    if user_metric:
        # Find the most suitable diet plan based on BMI and gender
        suitable_diet_plan = DietPlan.objects.filter(
            min_bmi__lte=user_metric.bmi,
            max_bmi__gte=user_metric.bmi,
            gender__in=[user_metric.gender, 'A']
        ).first()

        user_diet_plan, created = UserDietPlan.objects.get_or_create(user=request.user)
        if user_diet_plan.diet_plan != suitable_diet_plan:
            user_diet_plan.diet_plan = suitable_diet_plan
            user_diet_plan.save()

    else:
        suitable_diet_plan = None

    return render(request, 'diet/user_diet_plan.html', {'diet_plan': suitable_diet_plan, 'user_metric': user_metric})

fitnessfirst/templates/diet/user_diet_plan.html
{% extends "app/base.html" %}

{% block content %}
<section class="base" id="base">
  <h3>Your Diet Plan</h3>


    {% if user_metric %}
        <p><strong>Your BMI:</strong> {{ user_metric.bmi }}</p>
        <p><strong>Your Gender:</strong> {{ user_metric.get_gender_display }}</p>
        <br/>

        <p><span><strong>Here is your personalized diet plan according to your Fitness Metrics</strong></span></p>

        <br/>


        {% if diet_plan %}

            <div class="diet_page" id="diet_page">

                <div class="diet" id="diet">
                    <p><span>Meal:</span> {{ diet_plan.title }}</p>
                </div>

                <div class="diet" id="diet">
                    <p><span>Diet Plan:</span> {{ diet_plan.description }}</p>
                </div>
    
                <div class="diet" id="diet">
                    <p><span>Calories Per Day:</span> {{ diet_plan.calories_per_day }}</p>
                </div>

                {% comment %} <div class="diet" id="diet">
                    <p><span>Diet Assigned By:</span> {{ diet_plan.assigned_by }}</p>
                </div> {% endcomment %}

            </div>
    
        {% else %}

            <p>Sorry, no suitable diet plan was found for your BMI and gender.</p>

        {% endif %}

    {% comment %} <p>You have not been assigned any diet plan yet.</p> {% endcomment %}

    {% else %}
      <p>Please calculate your fitness metrics to get a recommended diet plan.</p>
      <a href="{% url 'metrics:calculate_metrics' %}" class="btn">Calculate Metrics</a>

  {% endif %}

</section>
{% endblock %}